# Generated by Django 6.0.5 on 2026-05-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_admin', models.CharField(max_length=20)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=14, null=True)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField()),
                ('nome_admin', models.CharField(max_length=100)),
                ('email_admin', models.CharField(max_length=100, unique=True)),
                ('senha_admin', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id_apartamento', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('placa_veiculo', models.CharField(blank=True, max_length=7, null=True)),
                ('bloco', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'apartamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaReserva',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_area', models.CharField(max_length=50)),
                ('regras', models.TextField()),
                ('taxa_reserva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'area_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id_comunicado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_comunicado', models.CharField(max_length=16)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'comunicado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id_encomenda', models.AutoField(primary_key=True, serialize=False)),
                ('chegada', models.DateTimeField()),
                ('status_encomenda', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'encomenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('data_escala', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'escala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('email_funcionario', models.CharField(max_length=100, unique=True)),
                ('senha_funcionario', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id_morador', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_morador', models.CharField(max_length=11)),
                ('nome_morador', models.CharField(max_length=100)),
                ('email_morador', models.CharField(max_length=100, unique=True)),
                ('senha_morador', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'morador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ocorrencia', models.CharField(max_length=19)),
                ('status_ocorrencia', models.CharField(max_length=12)),
                ('descricao_ocorrencia', models.CharField(max_length=300)),
                ('data_ocorrencia', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id_reclamacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reclamacao', models.CharField(max_length=19)),
                ('descricao', models.CharField(max_length=300)),
                ('data_reclamacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reclamacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TimeField()),
                ('data_reserva', models.DateField()),
                ('motivo_reserva', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('acesso', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
    ]
