# Generated by Django 6.0.5 on 2026-06-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('morador', '0004_ocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('acesso', models.CharField(max_length=10, unique=True)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Registrada', 'Registrada')], default='Agendada', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_validadas', to='funcionario.funcionario')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='morador.morador')),
            ],
            options={
                'db_table': 'visita',
            },
        ),
    ]
