# Generated by Django 6.0.5 on 2026-06-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_comunicado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comunicado',
        ),
    ]
