# Generated by Django 6.0.5 on 2026-06-05 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrador", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bloco", models.CharField(max_length=5)),
                ("andar", models.CharField(max_length=3)),
                ("numero", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "apartamento",
            },
        ),
        migrations.CreateModel(
            name="Morador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
                ("telefone", models.CharField(max_length=11)),
                (
                    "tipo_morador",
                    models.CharField(
                        choices=[
                            ("Inquilino", "Inquilino"),
                            ("Proprietario", "Proprietario"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "administrador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrador.administrador",
                    ),
                ),
                (
                    "apartamento",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="morador.apartamento",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "morador",
            },
        ),
    ]
