# Generated by Django 6.0.5 on 2026-06-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('tipo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Outro', 'Outro')], max_length=10)),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='morador.apartamento')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
    ]
