# Generated by Django 6.0.5 on 2026-06-10 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_delete_comunicado'),
        ('morador', '0002_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Barulho', 'Barulho'), ('Limpeza', 'Limpeza'), ('Infraestrutura', 'Infraestrutura'), ('Segurança', 'Seguranca'), ('Outro', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('em analise', 'Em análise'), ('negada', 'Negada'), ('validada', 'Validada')], default='em analise', max_length=15)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes', to='administrador.administrador')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes', to='morador.apartamento')),
            ],
            options={
                'db_table': 'reclamacao',
            },
        ),
    ]
