# Generated by Django 6.0.5 on 2026-06-10 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_delete_comunicado'),
        ('morador', '0003_reclamacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(choices=[('Advertência', 'Advertencia'), ('Multa', 'Multa'), ('Barulho', 'Barulho'), ('Limpeza', 'Limpeza'), ('Outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_registradas', to='administrador.administrador')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='morador.apartamento')),
            ],
            options={
                'db_table': 'ocorrencia',
            },
        ),
    ]
