# Generated by Django 6.0.5 on 2026-06-10 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('regras', models.CharField(max_length=500)),
                ('taxa_reserva', models.FloatField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
