# Generated by Django 6.0.5 on 2026-06-10 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('area', '0001_initial'),
        ('morador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField()),
                ('motivo', models.CharField(max_length=500)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.morador')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
