# Generated by Django 6.0.5 on 2026-06-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('aberto', 'Pendente'), ('negado', 'Negado'), ('aprovado', 'Aprovado')], default='aberto', max_length=8),
        ),
    ]
