# Generated by Django 6.0.5 on 2026-06-11 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0003_delete_comunicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Manutenção', 'Manutencao'), ('Assembleia', 'Assembleia'), ('Segurança', 'Seguranca'), ('Evento', 'Evento'), ('Urgente', 'Urgente'), ('Financeiro', 'Financeiro'), ('Convivencia', 'Convivencia'), ('Falta de agua', 'Falta Agua'), ('Falta de energia', 'Falta Energia')], max_length=16)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
            ],
            options={
                'db_table': 'comunicado',
            },
        ),
    ]
